### ISSUE TITLE
cant seem to get a trend line in?

### ISSUE THREAD

**Issue by lexifern** [lexifern/ProjectAres#2]
library(ggplot2)
library(grid)
library(dplyr)

# Plot Installations

plot1 <- ggplot(data=SM, aes(x=Quarterly, y=Installations)) + 
  geom_smooth(method=lm)+
  geom_line(aes(group=2), colour="#00BFC4") +        
  geom_point(size=2, colour="#00BFC4")    +      
   #dot colour
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=0.5))   # angle of labels on x axis
SMD1 + ggtitle("Smart meter installations by quarter")             #title

# Plot Demand

 plot2<-ggplot(data=SM, aes(x=Quarterly, y=Demand)) + 
   geom_line(aes(group=2)) +             # Line colour
   geom_point(size=2)    +                    #dot colour
   theme(axis.text.x=element_text(angle=45,hjust=1,vjust=0.5))   # angle of labels on x axis
 SMD1 + ggtitle("Demand")             #title
 

grid.newpage()
grid.draw(rbind(ggplotGrob(plot1), ggplotGrob(plot2), size = "last"))

**Comment by rhydianpageons** [comment]
## the only issue here is that Quarter in the data is a factor, so you need to tell R to change it to numeric.
##then the geom_smoth will work

plot1 <- ggplot(data=SM, aes(x=as.numeric(Quarter), y=All)) +
  geom_smooth(method=lm, se= FALSE)+
  geom_line(aes(group=2), colour="#00BFC4") +
  geom_point(size=2, colour="#00BFC4") +
  #dot colour
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=0.5)) + # angle of labels on x axis
  ggtitle("Smart meter installations by quarter") #title
plot1

**Comment by lexifern** [comment]
amazing!! All sorted now - thank you
